sudo: enabled
dist: trusty

language: java
jdk:
  - oraclejdk11

script:
  - ./gradlew clean build jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - serhii.s.korol@gmail.com
